config/routes.rb
Rails.application.routes.draw do
  devise_for :managers, only: [:sign_in, :sign_out, :session]
  resources :managers do
    member do
      get 'relations'
    end
  end

  devise_for :users
  devise_scope :user do
      root :to => "users/sessions#new"
  end


  resources :pams_answers, only: [:index, :show, :edit, :update, :create]
  resources :users, only: [:edit, :update, :new, :create]


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/pams_answer.rb
class PamsAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :manager

end

app/controllers/pams_answers_controller.rb
class PamsAnswersController < ApplicationController
  before_action :set_pams_answer, only: [:show, :edit, :update]
  before_action :set_q_a, only: [:edit]

  #非ログイン時サインイン画面にリダイレクト
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :authenticate_manager!, only: [:create]

  def create
    @new_pamsanswer = PamsAnswer.create(create_params)
    redirect_to controller: 'managers', action: 'index'
  end

  def index
    @pams_answers = PamsAnswer.where(user_id: current_user.id)
  end

  # GET /pams_answers/1_1
  def show
    @result = result(@pams_answer)

    @result_4_ave = 100 - ((@result[1] + @result[2] + @result[3] + @result[4]) * 100 / (@result[1] + @result[2] + @result[3] + @result[4] + @result[6] + @result[7] + @result[8] + @result[9]))

    @result_4 = @result.values_at(2, 8, 3, 7)
    @condition_branch_1 = condition_branch_1(@result_4)

    @condition_branch_2_1 = condition_branch_2_1(@result_4_ave, page_2_1)
    @condition_branch_2_2 = condition_branch_asc(@result[2], page_2_2)
    @condition_branch_2_3 = condition_branch_asc(@result[3], page_2_3)
    @condition_branch_2_4 = condition_branch_asc(@result[7], page_2_4)
    @condition_branch_2_5 = condition_branch_asc(@result[8], page_2_5)

    @condition_branch_3_1 = condition_branch_desc(@result[0], page_3_1)
    @condition_branch_3_2 = condition_branch_desc(@result[1], page_3_2)
    @condition_branch_3_3 = condition_branch_desc(@result[4], page_3_3)
    @condition_branch_3_4 = condition_branch_desc(@result[5], page_3_4)
    @condition_branch_3_5 = condition_branch_desc(@result[6], page_3_5)
    @condition_branch_3_6 = condition_branch_desc(@result[9], page_3_6)

    @condition_branch_4_1_1 = condition_branch_4_1_1(@result[0], @result[1], @result[6], @result[5], @result[9], @result[4])
    @condition_branch_4_1_2 = condition_branch_4_1_2(@condition_branch_4_1_1, page_4_1)

    @condition_branch_4_2 = condition_branch_asc(@result[0], page_4_2)
    @condition_branch_4_3 = condition_branch_asc(@result[1], page_4_3)
    @condition_branch_4_4 = condition_branch_asc(@result[6], page_4_4)
    @condition_branch_4_5 = condition_branch_asc(@result[5], page_4_5)
    @condition_branch_4_6 = condition_branch_asc(@result[9], page_4_6)
    @condition_branch_4_7 = condition_branch_asc(@result[4], page_4_7)

  end


  # GET /pams_answers/1/edit
  def edit
  end

  # PATCH/PUT /pams_answers/1
  def update
    respond_to do |format|
      if @pams_answer.update(pams_answer_params)
        format.html { redirect_to @pams_answer, notice: 'Pams answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @pams_answer }
      else
        format.html { render :edit }
        format.json { render json: @pams_answer.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pams_answer
      @pams_answer = PamsAnswer.find(params[:id])
    end

    #下記メソッドを各インスタンス変数に格納
    def set_q_a
      @questions_1_100 = questions_1_100
      @questions_101_130 = questions_101_130
      @questions_131_140 = questions_131_140
      @questions_141_150 = questions_141_150
      @answers_1_100 = answers_1_100
      @answers_101_130 = answers_101_130
      @answers_131_140 = answers_131_140
      @answers_141_150 = answers_141_150
    end

    def create_params
      params.require(:pams_answer).permit(:user_id).merge(fin_flag: false).merge(manager_id: current_manager.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pams_answer_params
      #ApplicationController privatemethod
      q_1_150 = q_xxx(1, 150)

      #バリデーション
      params.require(:pams_answer)
            .permit(*q_1_150)
            .merge(user_id: current_user.id)
            .merge(fin_flag: true)
    end


    def condition_branch_1(result)
      check_up_box_1
      if result[0] >= 55
        if result[1] < 55
          if result[2] < 55
            if result[3] < 55
              return check_up_box_1[0]
            else
              return check_up_box_1[1]
            end
          else
            if result[3] < 55
              return check_up_box_1[2]
            else
              return check_up_box_1[3]
            end
          end
        else
          if result[2] < 55
            if result[3] < 55
              return check_up_box_1[4]
            else
              return check_up_box_1[5]
            end
          else
            if result[3] < 55
              return check_up_box_1[6]
            else
              return check_up_box_1[7]
            end
          end
        end
      else
        if result[1] < 55
          if result[2] < 55
            if result[3] < 55
              return check_up_box_1[8]
            else
              return check_up_box_1[9]
            end
          else
            if result[3] < 55
              return check_up_box_1[10]
            else
              return check_up_box_1[11]
            end
          end
        else
          if result[2] < 55
            if result[3] < 55
              return check_up_box_1[12]
            else
              return check_up_box_1[13]
            end
          else
            if result[3] < 55
              return check_up_box_1[14]
            else
              return check_up_box_1[15]
            end
          end
        end
      end
    end

    def condition_branch_desc(result, box)
      if result <= 45
        return box[2]
      elsif 45 < result && result <= 65
        return box[1]
      elsif 65 < result
        return box[0]
      end
    end

    def condition_branch_asc(result, box)
      if result <= 45
        return box[0]
      elsif 45 < result && result <= 65
        return box[1]
      elsif 65 < result
        return box[2]
      end
    end

    def condition_branch_2_1(result, box)
      if result <= 45
        return box[0]
      elsif 45 < result && result <= 55
        return box[1]
      elsif 55 < result
        return box[2]
      end
    end

    def condition_branch_4_1_1(result_1, result_2, result_3, result_4, result_5, result_6)
      if result_1 <= 45
        ele_1 = 2
      elsif 45 < result_1 && result_1 <= 65
        ele_1 = 1
      elsif 65 < result_1
        ele_1 = 0
      end

      if result_2 <= 45
        ele_2 = 2
      elsif 45 < result_2 && result_2 <= 65
        ele_2 = 1
      elsif 65 < result_2
        ele_2 = 0
      end

      if result_3 <= 45
        ele_3 = 2
      elsif 45 < result_3 && result_3 <= 65
        ele_3 = 1
      elsif 65 < result_3
        ele_3 = 0
      end

      if result_4 <= 45
        ele_4 = 2
      elsif 45 < result_4 && result_4 <= 65
        ele_4 = 1
      elsif 65 < result_4
        ele_4 = 0
      end

      if result_5 <= 45
        ele_5 = 2
      elsif 45 < result_5 && result_5 <= 65
        ele_5 = 1
      elsif 65 < result_5
        ele_5 = 0
      end

      if result_6 <= 45
        ele_6 = 2
      elsif 45 < result_6 && result_6 <= 65
        ele_6 = 1
      elsif 65 < result_6
        ele_6 = 0
      end
      return 12 - (ele_1 + ele_2 + ele_3 + ele_4 + ele_5 + ele_6)
    end

    def condition_branch_4_1_2(result, box)
      if result <= 4
        return box[2]
      elsif 4 < result && result <= 8
        return box[1]
      elsif 8 < result
        return box[0]
      end
    end

#回答
    def answers_1_100
      {

5 => '5',
4 => '4',
3 => '3',
2 => '2',
1 => '1'

      }
    end

    def answers_101_130
      {

10 => '10',
9 => '9',
8 => '8',
7 => '7',
6 => '6',
5 => '5',
4 =>'4',
3 => '3',
2 => '2',
1 => '1'

      }
    end

    def answers_131_140
      {

10 => '10',
9 => '9',
8 => '8',
7 => '7',
6 => '6',
5 => '5',
4 =>'4',
3 => '3',
2 => '2',
1 => '1'

      }
    end

    def answers_141_150
      {

10 => '1',
9 => '2',
8 => '3',
7 => '4',
6 => '5',
5 => '6',
4 =>'7',
3 => '8',
2 => '9',
1 => '10'

      }
    end

#質問
    def questions_1_100
      {

q_001: '仕事は皆のためにするものだと思う',
q_002: '気分は比較的安定している',
q_003: '考えるより、行動しながら修正していく',
q_004: '自分と違うタイプの人ならば、少し警戒することが多い',
q_005: '生まれ変わるとしたら、違う人生が良い',
q_006: '毎日の生活は充実している',
q_007: '「個性的」という言葉は褒め言葉だと思う',
q_008: '仲の良い友人でも、自分の全てを開示することはしない',
q_009: '周囲の人間が敵に見えることがある',
q_010: '常に誰かと一緒にいないと寂しいと感じる',
q_011: '結果まで予想できないと、物事を始められない',
q_012: '人の意見はしっかりと尊重する',
q_013: '人前で話すことは、苦手ではない',
q_014: '友人を作るときには自分から積極的に話しかける方である',
q_015: '他の人が自分よりも優秀に見えることが多い',
q_016: '自分で決断するよりも、決まったことに従う方が楽である',
q_017: '宴会などでは幹事を任されることが多い',
q_018: 'タイムマネジメントを意識することが多い',
q_019: '人間で大切なのは内面であり、外面は関係ないと思う',
q_020: '涙もろい方である',
q_021: 'ミスをするとひきずる方である',
q_022: '他人の考えを認めることは容易である',
q_023: '計画を立てたら、時折見直すことが大切である',
q_024: '一人でいるほうが気持ちが落ち着く',
q_025: '反省はするより、具体的に次に向けて動き出す',
q_026: 'リラクセーション法を自分なりに持っている',
q_027: '人の話を最後まで聞くのが苦手である',
q_028: '妄想をすることが多い',
q_029: '自分は人よりも優れていることが多いと思う',
q_030: '家族とは喧嘩をしたりすることはない',
q_031: '勝負事には他人を押しのけてでも勝ちたい',
q_032: '怒ると怖いと言われる',
q_033: '同情を得るために自分の不幸を伝える人は多いと思う',
q_034: 'たまには下品な冗談で笑うこともある',
q_035: '自分の意見はしっかりと人に伝えるべきだ',
q_036: '人にやさしく接するのに理由などいらない',
q_037: '損をするぐらいなら、多くの人は不正な手段をつかってでもそれを阻止すると思う',
q_038: '自分がなぜ怒っているのか、わからなくなることがある',
q_039: '物事は一人で進めたい',
q_040: '選挙の際に、よく知らない候補者に投票したことがある',
q_041: '人には言えないようなことを考えることがある',
q_042: '自分の選んだ道を家族から反対されることがあった',
q_043: '人のうわさ話をすることが時折ある',
q_044: '体調が悪いときには怒りっぽい',
q_045: '法律や条例は全てなくなった方が良いと思う',
q_046: '失敗することを想像して心配になることが多い',
q_047: '人より優れていると感じている',
q_048: '多くの人と仕事をしてみたいと思う',
q_049: '真面目に働く意志があれば、成功できると思う',
q_050: '生まれ変わりを確信している',
q_051: '色々な人と知り合いにあるのは楽しいと思う',
q_052: '人が多いところでは、引っ込み思案になる',
q_053: '難局になった場合は動きながら対応していく',
q_054: '私に嫉妬をする人は少なくない',
q_055: '周囲の人と調子を合わせることが多い',
q_056: 'いつも何かをしていないと落ち着かない方である',
q_057: '世の中の人は、他人にことを気にしていないと思う',
q_058: '理由なく、喜んだり悲しんだりする',
q_059: '人が見てくれていると思うと、がんばれる',
q_060: '私の行動は人に影響を与えることが多い',
q_061: '感情が顔に出てしまうことが多い',
q_062: '時々、何をしていても興味を持てないことがある',
q_063: '知らない人と話すときには緊張する',
q_064: 'イベントなどでは率先垂範を意識している',
q_065: '計画を立てるよりもまず行動する',
q_066: '短時間に他の人よりも多くの仕事ができる',

app/helpers/pams_answers_helper.rb
module PamsAnswersHelper
end

app/views/pams_answers/_form.html.erb
<%= stylesheet_link_tag "pams/radio_button", :media => "all" %>

<%= form_with(model: pams_answer, local: true) do |form| %>

<table class="form_table">
  <hr>
  <h1>
    Q1〜Q100:以下の質問項目について、当てはまるものを選んでください。
  </h1>
  <hr>
  <tr class="th_tr">
    <th class="_q_">
    <th class="q_th">
    </th>
    <th class="form_th">
      <div class="node_th">
        <div style="float: left">当てはまる</div>
        <div style="text-align: right">当てはまらない</div>
      </div>
    </th>
  </tr>
  <% @questions_1_100.each.with_index(1) do |(q_key, q_value), q_i| %>
      <tr class="td_tr">
      <td>Q<%= q_i %></td>
      <td><label><%= q_value %></label></td>
      <td class="form">
        <div class="nodes">
        <% @answers_1_100.each do |a_key, a_value| %>
            <div class="node">
              <%= form.radio_button q_key, a_key, required: true, class: "form__radio", type: "radio" %>
              <label class="form__label" for="pams_answer_<%= q_key %>_<%= a_key %>"><span class="indicator"><%= a_value %></span></label>
            </div>
        <% end %>
        </div>
      </td>
      </tr>
  <% end %><br/>
</table>

<h1><br></h1>

  <hr>
  <h1>
    Q101〜Q130: 以下の質問についてあてはまる評価を選んでください。
  </h1>
  <hr>
<table class="form_table">
  <tr class="th_tr">
    <th class="_q_">
    </th>
    <th class="q_th">
    </th>
    <th class="form_th">
      <div class="node_th">
        <div style="float: left">当てはまる</div>
        <div style="text-align: right">当てはまらない</div>
      </div>
    </th>
  </tr>
  <% @questions_101_130.each.with_index(101) do |(q_key, q_value), q_i| %>
      <tr class="td_tr">
      <td>Q<%= q_i %></td>
      <td><label><%= q_value %></label></td>
      <td class="form">
        <div class="nodes">
        <% @answers_101_130.each do |a_key, a_value| %>
            <div class="node">
              <%= form.radio_button q_key, a_key, required: true, class: "form__radio", type: "radio" %>
              <label class="form__label" for="pams_answer_<%= q_key %>_<%= a_key %>"><span class="indicator"><%= a_value %></span></label>
            </div>
        <% end %>
        </div>
      </td>
      </tr>
  <% end %><br/>
</table>


<h1><br></h1>

  <hr>
  <h1>
    Q131〜Q140: 以下の10項目についてあてはまる評価を選んでください。(10点満点)
  </h1>
  <hr>

<table class="form_table">
  <tr class="th_tr">
    <th class="_q_">
    </th>
    <th class="q_th">
    </th>
    <th class="form_th">
      <div class="node_th">
        <div style="float: left">当てはまる</div>
        <div style="text-align: right">当てはまらない</div>
      </div>
    </th>
  </tr>
  <% @questions_131_140.each.with_index(131) do |(q_key, q_value), q_i| %>
      <tr class="td_tr">
      <td>Q<%= q_i %></td>
      <td><label><%= q_value %></label></td>
      <td class="form">
        <div class="nodes">
        <% @answers_131_140.each do |a_key, a_value| %>
            <div class="node">
              <%= form.radio_button q_key, a_key, required: true, class: "form__radio", type: "radio" %>
              <label class="form__label" for="pams_answer_<%= q_key %>_<%= a_key %>"><span class="indicator"><%= a_value %></span></label>
            </div>
        <% end %>
        </div>
      </td>
      </tr>
  <% end %><br/>
</table>

<h1><br></h1>
  <hr>
  <h1>
    Q141〜Q150: 以下の10項目に順位をつけてください。
  </h1>
  <hr>

<table class="form_table">
  <tr class="th_tr">
    <th class="_q_">
    </th>
    <th class="q_th">
    </th>
    <th class="form_th">
      <div class="node_th">
        <div style="float: left">1位</div>
        <div style="text-align: right">10位</div>
      </div>
    </th>
  </tr>
  <% @questions_141_150.each.with_index(141) do |(q_key, q_value), q_i| %>
      <tr class="td_tr">
      <td>Q<%= q_i %></td>
      <td><label><%= q_value %></label></td>
      <td class="form">
        <div class="nodes">
        <% @answers_141_150.each do |a_key, a_value| %>
            <div class="node">
              <%= form.radio_button q_key, a_key, required: true, class: "form__radio", type: "radio" %>
              <label class="form__label" for="pams_answer_<%= q_key %>_<%= a_key %>"><span class="indicator"><%= a_value %></span></label>
            </div>
        <% end %>
        </div>
      </td>
      </tr>
  <% end %><br/>
</table>
  

  <%= form.hidden_field :fin_flag, :value => true %><br/>

  <%= form.hidden_field :user_id, value: current_user.id %><br/>

  <div class="actions">
    <%= form.submit "回答を送信する", class: "actions-button", type: "submit" %>
  </div>
<% end %>

app/views/pams_answers/edit.html.erb
<div class="wrapper">


<%= render 'form', pams_answer: @pams_answer %>

<%= link_to 'ホーム画面へ戻る', pams_answers_path %>

</div>

app/views/pams_answers/index.html.erb
<%= stylesheet_link_tag "pams/temporary", :media => "all" %>

<center>
<h3>ようこそ<%= current_user.email %>さん</h3>


<table>
  <tbody>
    <% @pams_answers.each do |pams_answer| %>
      <tr>
        <% if pams_answer.fin_flag == false %>
          <td><h2>＜重要＞アンケートに回答お願いします</h2></td>
          <td><%= pams_answer.created_at %></td>
          <td><%= link_to '回答する', edit_pams_answer_path(pams_answer) %></td>
        <% else %>
          <td></td>
          <td><%= pams_answer.created_at %></td>
          <td><%= link_to '※回答済み※', pams_answer %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</center>